more details
htmlacademy-javascript/1646629-keksobooking-23 pull request #3
Opened 2021-06-12 16:24 UTC by milevskiyTG

2021-06-14 06:35 UTC, polina-prokofieva requested changes
В целом, хорошо, но есть пару замечений.

2021-06-14 06:35 UTC, polina-prokofieva commented on js/main.js
> +randomNumber(1, 100, 2);
Убери, пожалуйста, эти вызовы. В прошлом задании они были нужны, чтобы линт не ругался, сейчас эти функции используются уже по назначению, а этот код уже лишний.

2021-06-14 06:35 UTC, polina-prokofieva commented on js/main.js
> +  };
Давай сократим этот код до такого:
```
return (index >= 10) ? `img/avatars/user${index}.png`: `img/avatars/user0${index}.png`;
```

2021-06-14 06:35 UTC, polina-prokofieva commented on js/main.js
> +    lng: randomNumber(MIN_LNG, MAX_LNG, DECIMAL),
lng и lat тут не совпадают с теми, что в поле address (строка 49). Их нужно создать отдельно, а потом использовать в двух местах, чтобы они были одинаковые.

2021-06-14 06:35 UTC, polina-prokofieva commented on js/main.js
> +    photos: PHOTOS[randomPhoto],
По условию, photos - это не одна строка, а массив строк случайной длины.

2021-06-14 06:35 UTC, polina-prokofieva commented on js/main.js
> +    description: DESCRIPTION[randomDescription],
Тут всё работает правильно. Но, по сути, ты несколько раз повторяешь одни и те же операции - получаешь случайное число, от нуля до длины массива, а потом получаешь жлемент из этого же массива. Тебе нужно написать функцию для получения случайного числа в массиве (например `getRandomElementFromArray(array)`), которая и будет делать эти две операции.

2021-06-16 06:59 UTC, polina-prokofieva requested changes
Уже намного лучше и аккуратнее! Почти идеально! И я бы с радостью приняла задание, но есть один очень важный момент, который нужо исправить, потому что иначе не получится реализовать одно из следующих заданий.

2021-06-16 07:08 UTC, milevskiyTG commented
Какой момент, не подскажите?

2021-06-16 07:08 UTC, polina-prokofieva requested changes

2021-06-16 07:08 UTC, polina-prokofieva commented on js/main.js
> +const PHOTOS = ['https://assets.htmlacademy.ru/content/intensive/javascript-1/keksobooking/duonguyen-8LrGtIxxa4w.jpg',
Вынеси, пожалуйста, константы в начало файла ([Критерий Б10](https://up.htmlacademy.ru/javascript/23/criteries#b10))

2021-06-16 07:08 UTC, polina-prokofieva commented on js/main.js
> +const lng = randomNumber(139.70000, 139.80000, 5);
Вот то место, которое очень важно исправить. Тут у тебя формируются случайный значения lat и lng, а потом эти значения (одни и те же) добавляются во все объекты. А нужно, чтобы эти значения были разными для каждого объекта объявления. Для этого нужно эти строки перенести в начало функции createAd. А в функции createOffer и createLocation передавать их в качестве параметра.

2021-06-16 07:08 UTC, polina-prokofieva commented on js/main.js
> +const createOffer = function(){
Вот здесь нужно добавить параметры:
```
const createOffer = function(lng, lat)
```

2021-06-16 07:08 UTC, polina-prokofieva commented on js/main.js
> +const createLocation = function(){
И вот тут:
```
const createLocation = function(lng, lat)
```

2021-06-16 07:08 UTC, polina-prokofieva commented on js/main.js
> +const createAd = function(amount){
А вот сюда нужно перенести получение случайных значений для `lng` и `lat`

2021-06-16 18:25 UTC, polina-prokofieva approved these changes

2021-06-16 18:25 UTC, merged